### ISSUE TITLE
use python 3.7 stable ABI

### ISSUE THREAD

**Issue by ritchie46** [conda-forge/polars-feedstock#13]
### Comment:

Upstream we build the binaries with python 3.7's stable ABI. This ensures that any python version `>= 3.7` can run the wheel and thus save a lot of build hours and repository storage.

Is that something we want here as well?

**Comment by Maxyme** [comment]
As far as I'm aware, packages are built for every supported python version and OS and python interpreter (cython or pypy). This should mean maximum compatibility. I think that there also might be a performance penalty to using the limited API: https://docs.python.org/3/c-api/stable.html.
Since builds are parallel, having more should not really be that much slower.

**Comment by xhochy** [comment]
We are building with the stable ABI but there is currently no easy way to mark Python-based conda packages as native-to-the-platform-but-open-to-all-newer-Python-versions. For the sake of maintenance, I would keep building the individual packages here until we have a conda-forge wide solution on how to deal with stable ABI packages.

**Comment by ritchie46** [comment]
Alright, make sense. :+1:
